# Generated by Django 5.2.1 on 2025-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retiro en tienda'), ('DOMICILIO', 'Despacho a domicilio')], default='RETIRO', max_length=20),
        ),
    ]
