# Generated by Django 5.2.1 on 2025-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
